//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace THIDinhVu_61131562.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class SinhVien
    {
        [DisplayName("Mã sinh viên")]
        [Required(ErrorMessage = "Chưa nhập dữ liệu")]
        public string MaSV { get; set; }
        [Required(ErrorMessage = "Chưa nhập dữ liệu")]
        public string HoSV { get; set; }
        [Required(ErrorMessage = "Chưa nhập dữ liệu")]
        public string TenSV { get; set; }
        [Required(ErrorMessage = "Chưa nhập dữ liệu")]
        public Nullable<bool> GioiTinh { get; set; }
        [Required(ErrorMessage = "Chưa nhập dữ liệu")]
        public Nullable<System.DateTime> NgaySinh { get; set; }

        public string AnhSV { get; set; }

        public string DiaChi { get; set; }

        public string TonGiao { get; set; }

        public string DanToc { get; set; }

        public string SDT { get; set; }

        public string CMND { get; set; }

        public string HeDT { get; set; }

        public string HoTenCha { get; set; }

        public Nullable<System.DateTime> NgaySinhCha { get; set; }

        public string NgheNghiepCha { get; set; }

        public string HoTenMe { get; set; }

        public Nullable<System.DateTime> NgaySinhMe { get; set; }

        public string NgheNghiepMe { get; set; }

        public string Email { get; set; }

        public string MaLop { get; set; }

        public string MaNganh { get; set; }


        public virtual Lop Lop { get; set; }

        public virtual NganhHoc NganhHoc { get; set; }
    }
}
