//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KT0720Vu_61131562.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class SinhVien
    {
        [Required(ErrorMessage = "Chưa nhập dữ liệu")]
        public string MaSV { get; set; }
        [Required(ErrorMessage = "Chưa nhập dữ liệu")]
        public string HoSV { get; set; }
        [Required(ErrorMessage = "Chưa nhập dữ liệu")]
        public string TenSV { get; set; }
        public Nullable<bool> GioiTinh { get; set; }
        [Required(ErrorMessage = "Chưa nhập dữ liệu")]
        public Nullable<System.DateTime> NgaySinh { get; set; }
        public string AnhSV { get; set; }
        public string DiaChi { get; set; }
        public string MaLop { get; set; }
    
        public virtual Lop Lop { get; set; }
    }
}
